#!/bin/bash

# this should probably be done in go/python/something
# this is just a POC

ID=$1

if [ -z "$ID" ]; then
    if [ -f /etc/machine_id ]; then
        ID=`cat /etc/machine_id`
    fi
fi

if [ -z "$ID" ]; then
    if [ -r /sys/class/dmi/id/product_uuid ]; then
        ID=`cat /sys/class/dmi/id/product_uuid`
    fi
fi

if [ -z "$ID" ]; then
    echo "need an ID!!!"
    exit -5
fi

ADIR=/tmp/ansible
mkdir -p $ADIR

cat <<EOF > $ADIR/hosts
$ID ansible_connection=local
EOF

mkdir -p $ADIR/host_vars

cat << EOF > $ADIR/host_vars/$ID
---
machine_id: $ID
EOF

for S in tftpd dhcpd;  do
    ENABLE="false"
    V=`etcdctl get /lochness/hypervisors/$ID/config/$S 2>&1`
    if [ $? -eq 0 ]; then
        V=${V,,}
        case $V in
            true|1|yes)
                ENABLE="true"
                ;;
            *)
                ;;
        esac
    fi
    printf "%s_enable: %s\n"  $S $ENABLE >> $ADIR/host_vars/$ID
done

ansible-playbook --inventory $ADIR/hosts --connection=local ./lochness.yml
